---
- hosts: all
  become_user: True
  tasks:
    #- name: Install latest version of Apache
    #  shell: sudo mkdir sample5
    - name: Install Apache2
      shell: sudo apt install apache2
    - name: Stop Apache2
      shell: sudo systemctl stop apache2
    - name: Stop Apache2
      shell: sudo systemctl restart apache2  
    - name: Deploy Static Website
      copy:
        src: index.html
        dest: /var/www/html/   
      
