---
- hosts: all
  become_user: true
  tasks:
    #- name: Install latest version of Apache
    #  shell: sudo mkdir sample5
    - name: Install Apache2
      shell: sudo apt install apache2
    - name: Stop Apache2
      shell: sudo systemctl stop apache2
    - name: Stop Apache2
      shell: sudo systemctl restart apache2  
      #apt: name=apache2 update_cache=yes state=latest
   # - name: start Apache server
   #   service:
   #     name: httpd
   #     state: started
   #     enabled: True
   # - name: Deploy Static Website
   #   copy:
   #     src: index.html
   #     dest: /var/www/html/
